Feature/header
markorik/Beauty pull request #1
Opened 2021-02-28 13:52 UTC by markorik

2021-03-03 07:33 UTC, studenttsu requested changes
Привет) Спасибо за читый код!

Осталось дожать вёрстку шапки и отработать по рекомендациям.

2021-03-03 07:33 UTC, studenttsu commented on index.html
> +                            <img src="images/about-video.jpg" alt="">
`нужно прпавить`

не хватает текстового содержание, картинку лучше сделать фоном
хочу обратить внимание, что затемнение фона нужно делать стилями, ведь сама картинка может быть любой

2021-03-03 07:33 UTC, studenttsu commented on index.html
> +        <!-- Шапка -->
`отлично`

задокументированный код легче и приятней читать)
в css комментарии вставляются как `//` или `/* */`

2021-03-03 07:33 UTC, studenttsu commented on index.html
> +                    <a class="navstyle" href="/">Услуги и цены</a>
`можно лучше`

принято в html отделять слова через `-`, получится nav-style

2021-03-03 07:33 UTC, studenttsu commented on css/style.css
> +.navstyle {
`можно лучше`

общие стили принято хранить в верху файла стилей,
если у тебя будет много ссылок на странице - всем нужно будет добавить navstyle? Лучше просто на тег a накинуть - таким образом переопределишь дефолтное поведение ссылок

2021-03-06 03:08 UTC, markorik commented
Добрый день! Внесла правки в соответствии с замечаниями.
В блоке "О салоне" сначала не сделала часть с тремя картинками, т.к. подумала, что это вообще отдельный самостоятельный блок. Потом поняла ошибку и сделала отдельным коммитом (Correction in "About" block) уже после отправки пул-реквеста. Надеюсь, эти исправления тоже будет видно?

2021-03-06 10:10 UTC, studenttsu approved these changes

2021-03-06 10:37 UTC, merged