Js/second
markorik/Beauty pull request #6
Opened 2021-04-04 11:47 UTC by markorik

Добавила расширенную форму записи. Подключила валидацию полей и ввод телефона с использованием маски.
Данные из форм отправляются на сервер.

2021-04-06 12:28 UTC, studenttsu requested changes
Отличная работа! 
По js стоит некоторые моменты поправить

2021-04-06 12:28 UTC, studenttsu commented on site/src/index.html
> +                            <a href="#price" class="burger__link">УСЛУГИ И ЦЕНЫ</a>
`можно лучше`

Правильней будет задавать приведение к верхнему регистру через css

2021-04-06 12:28 UTC, studenttsu commented on site/src/index.html
> +            <p class="form__title form__thanks">Спасибо</p>
`нужно поправить`

Правильней будет объединить с свои контейнеры, а не навешивать на каждый элемент формы классы `form__thanks` и `form__record`

2021-04-06 12:28 UTC, studenttsu commented on site/src/js/forms/order-form.js
> +        let viz = this.formEl.querySelectorAll(tohide);
не совсем понятно что означает переменная `viz`, хорошо бы давать более понятные имена переменным, чтобы было легче читать код

2021-04-06 12:28 UTC, studenttsu commented on site/src/js/forms/order-form.js
> +        for (let i of viz) {
здесь будет элемент, не индекс
имя `i` не совсем удачное

2021-04-06 12:28 UTC, studenttsu commented on site/src/js/forms/order-form.js
> +        let viz = this.formEl.querySelectorAll(tohide);
а лучше менять значение у контейнера, не у каждого элемента

2021-04-06 12:28 UTC, studenttsu commented on site/src/js/forms/order-form.js
> +        }, 2000);
зачем здесь задержка в 2 секунды?

2021-04-06 12:28 UTC, studenttsu commented on site/src/js/main.js
> +  const showHidden = document.querySelectorAll('.show');
у нас открытие модалки будет отрабатывать автоматически из-за fancybox плагина
нам достаточно один раз проинициализировать форму OrderForm

2021-04-06 12:28 UTC, studenttsu commented on site/src/js/main.js
> +  const showHidden = document.querySelectorAll('.show');
Я бы понял, если бы мы передавали необходимые данные в форму. Сейчас в цикле смысла нет

2021-04-07 03:29 UTC, markorik commented on site/src/js/forms/order-form.js
> +        }, 2000);
Задержку оставила, чтобы успеть увидеть лоадер

2021-04-07 03:37 UTC, markorik commented on site/src/js/main.js
> +  const showHidden = document.querySelectorAll('.show');
Если инициализировать форму всего один раз, то она не обновляется, если пытаться записаться повторно. Т.е. записались, форма закрылась, открываем опять, а там "спасибо". Переключение видимости блока с вводом данных и блока "спасибо" происходит в конструкторе. А если добавить такое же переключение перед автоматическим закрытием формы, то получается, что форма перед закрытием некрасиво "мигнёт", меняя своё состояние. Я не нашла другого решения, кроме как инициализировать при каждом открытии модалки.

2021-04-09 11:49 UTC, studenttsu approved these changes

2021-04-11 14:01 UTC, merged